### ISSUE TITLE
Link error 403

### ISSUE THREAD

**Issue by hoangkhoi** [zlargon/google-tts#25]
I can not access link from module with error .
Access to translate.google.com was denied You don't have authorization to view this page.
HTTP ERROR 403

**Comment by Nachouiteq** [comment]
Same here. I also had problems in a project with the Youtube API at the same time this started. Maybe is a problem from google...

**Comment by zlargon** [comment]
Hi,

The information is not enough for me to look into the issue, but I believe this problem is not caused by the package. So far, `npm test` could pass all the tests on [Travis-CI](https://travis-ci.org/zlargon/google-tts).

This is not official library from google, and google might change their API anytime, so please always use the latest version.

Hope you solve the issue soon :)
