### ISSUE TITLE
404 on texts over 200 characters

### ISSUE THREAD

**Issue by minemidnight** [zlargon/google-tts#5]
Any text that is over 200 characters returns a URL that just 404's.

**Comment by zlargon** [comment]
Thanks for your report.
This is the limitation of Google TTS API (for free), and I will add the statement to README.

**Comment by minemidnight** [comment]
Is there a way to get multiple URLs and combine the streams to overcome this?

**Comment by zlargon** [comment]
Yes, that's exactly how "Google Translate" is doing on their website:

First, cut off the long paragraph into many small sentences, in order to make all the amount of characters (of sentences) less than 200.

Then, send requests to `Google Translate API` and play the audios in sequence.

![google-translate-network](https://user-images.githubusercontent.com/2791834/29106681-e24a5eec-7d08-11e7-82df-a7d1f4565875.png)

In my opinion, combining multiple URLs would be an up-level functionality, which is not suitable to be implemented here. However, I think there still are two things I can do:
1. Check the input: If the amount of characters is over 200, then throw an exception. This would be updated in next release `0.0.2`.

2. Add an example to deal with long characters, as same as "Google Translate" do in their website. Thus, the user can reference the sample codes.

Thanks for your great advise, and hope you would like it. 👍 
Leon

**Comment by zlargon** [comment]
1. Library has been upgraded to `0.0.2`

2. An example for long characters:
    https://github.com/zlargon/google-tts/blob/master/example/long-english-characters.js
